# deployment.yaml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-depl
spec:
  replicas: 2
  selector:
    matchLabels:
      app: docker
  template:
    metadata:
      labels:
        app: docker
    spec:
      containers:
        - name: test-container
          image: library/nextcloud
          imagePullPolicy: Always
          ports:
            - containerPort: 80
            - containerPort: 443
          resources:
              limits:
                cpu: "0.4"
                memory: "400Mi"
            requests:
              cpu: "100m"
              memory: "100Mi"
