# service.yaml

apiVersion: v1
kind: Service
metadata:
  name: test-service
spec:
  selector:
    app: docker
  ports:
    - protocol: TCP
      name: http
      port: 80
      targetPort: 80
    - protocol: TCP
      name: https
      port: 443
      targetPort: 443

  type: LoadBalancer
